baseURL = "https://example.org/"
languageCode = "en-us"
title = "Example Site"
theme = "blog-theme"
paginate = 5

disqusShortname = ""

googleAnalytics = ""
enableEmoji = true

pygmentsCodeFences = true

[author]
  name = "Author"
  avatar = "/images/avatar.jpeg"
  github = "https://github.com/username"
  gitlab = ""
  linkedin = ""

[params]
  favicon = ""

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "reading"
    name = "Reading"
    url = "/reading/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

