name = "blog-theme"
license = "MIT"
licenselink = "https://github.com/ndtho8205/blog-theme/blob/master/LICENSE.md"
description = "A Hugo theme for my personal blog."
homepage = "http://github.com/ndtho8205/blog-theme"
tags = []
features = []
min_version = "0.79.0"

[author]
  name = "Tho Nguyen"
  homepage = "http://ndtho8205.github.io"
